### ISSUE TITLE
Question list layout issue when no matches in search

### ISSUE THREAD

**Issue by magickaichen** [CodeMonkeys3111/Web#28]
Right now when there's no matches during the search, the container does not disappear correctly.
Will try to fix this in the future.

**Comment by magickaichen** [comment]
issue has been already solved by Dan

**Comment by aralph** [comment]
If you want to close an issue:
- Refer to code that closes the issue. Ideally, mention that a PR fixes an issue and the issue will automatically close. 
- Check if the issue actually solved. 

I checked, the issue is not solved.
Our current master does this:
![bildschirmfoto 2015-11-19 um 23 31 28](https://cloud.githubusercontent.com/assets/1174752/11274898/0239c234-8f16-11e5-86fa-d7924ae6a0fd.png)

I am being serious:
Do not simply close/merge/accept things without testing them!

**Comment by magickaichen** [comment]
Oh that's my bad, thought the issue has already been solved before, will also try to fix this after.
